name: Count lines of code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  count-lines:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Count Lines of Code (cloc)
      uses: djdefi/cloc-action@2
      
    - name: Upload cloc output as a build artifact
      uses: actions/upload-artifact@v1
      with:
        name: cloc
        path: cloc.txt
        
    - name: Extract total loc
      uses: actions/download-artifact@v1
      with:
        name: cloc
    - run: echo "::set-env name=LOC::${{ cat cloc.txt | tail -2 | head -1 | grep -oE "[0-9]+$" }}"
    - run: echo "::set-env name=TSTAMP::${{ date -u --iso-8601=seconds }}"
    - run: echo "::set-env name=REPO::${{ github.repository }}"
    
    #- env:
    #    LOC: ${{ cat cloc.txt | tail -2 | head -1 | grep -oE "[0-9]+$" }}
    #    TSTAMP: ${{ date -u --iso-8601=seconds }}
    #    REPO: github.repository
    #    JSON: "{ 'loc': $LOC, 'time': '$TSTAMP', 'repo': '$REPO' }"
    - run: echo $TSTAMP 
    #- run: echo "::set-env name=JSON::$('{"loc": '"$LOC"'}')"
    #- run: echo '{"loc": '$LOC'}'
    #- run: cat cloc.txt | tail -2 | head -1 | grep -oE "[0-9]+$" > loc.txt
    #- run: echo '{"loc": '"$LOC"', "time": "'"$(date -u --iso-8601=seconds)"'", "repo": "repo-name"}'
    #- name: Upload munging  output as a build artifact
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: loc
    #    path: loc.txt
