name: Count lines of code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  count-lines:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Count Lines of Code (cloc)
      uses: djdefi/cloc-action@master
      
    - name: Upload cloc output as a build artifact
      uses: actions/upload-artifact@v1
      with:
        name: cloc
        path: cloc.txt
        
    - name: Extract total loc
      uses: actions/download-artifact@v1
      with:
        name: cloc
    - run: cat cloc.txt | tail -2 | head -1 | grep -oE "[0-9]+$"
    
    - name: Upload munging  output as a build artifact
      uses: actions/upload-artifact@v1
      with:
        name: loc
        path: loc.txt
